import React from 'react';
import '@mantine/core/styles.css';
import {ColorSchemeScript, MantineProvider} from '@mantine/core';
import '../global.css';

export const metadata = {
	title: 'Meteo',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<ColorSchemeScript defaultColorScheme="light" />
			</head>
			<body>
				<MantineProvider defaultColorScheme="light">
					<div className="wrapper">{children}</div>
				</MantineProvider>
			</body>
		</html>
	);
}
